export enum PermissionType {
  CREATE_REPORT = 'CREATE_REPORT',
  READ_REPORT = 'READ_REPORT',
  UPDATE_REPORT = 'UPDATE_REPORT',
  DELETE_REPORT = 'DELETE_REPORT',
  CREATE_COMPANY = 'CREATE_COMPANY',
  READ_COMPANY = 'READ_COMPANY',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  DELETE_COMPANY = 'DELETE_COMPANY',
  OTHER = 'OTHER',
  READ_FAILURE = 'READ_FAILURE'
}
